name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check Docker version
      run: docker --version

    - name: Log in to Azure Container Registry
      run: az acr login --name [VIDLABS_ACR_NAME]

    - name: Build and push Docker image
      id: build_and_push
      run: |
        TAG=$(date +%s)
        docker build -t [VIDLABS_ACR_NAME].azurecr.io/vidlabs_prod:$TAG .
        docker push [VIDLABS_ACR_NAME].azurecr.io/vidlabs_prod:$TAG
        echo "::set-output name=tag::$TAG"